### ISSUE TITLE
Intended?

### ISSUE THREAD

**Issue by 1stvaliduser** [xzxADIxzx/Scheme-Size#17]
Is this gap intended?
![IMG_20220725_190336](https://user-images.githubusercontent.com/94375206/180823991-7d58ba35-3691-4d0e-a970-4af5dd5e22b3.jpg)

**Comment by 1stvaliduser** [comment]
And this button no longer disables shooting:
![IMG_20220725_190633](https://user-images.githubusercontent.com/94375206/180824653-e3d5ec44-73dd-4331-b0e9-d50a40b2ec1b.jpg)

**Comment by xzxADIxzx** [comment]
> And this button no longer disables shooting.
> Strange, I tested on my device and everything was fine.

I fixed it, wait for the next update
