### ISSUE TITLE
Crashes

### ISSUE THREAD

**Issue by RandomInsultedCoder** [xzxADIxzx/Scheme-Size#25]
so... i turn on mindustry and play and it says version index 21>=21<=????

**Comment by xzxADIxzx** [comment]
can you send a screenshot of the error?

**Comment by RandomInsultedCoder** [comment]
sure....
![Screenshot_150](https://user-images.githubusercontent.com/109095551/192156598-730105c0-1423-49d9-ad87-cec2b7903ac0.png)

**Comment by xzxADIxzx** [comment]
i mean... send me crash-report-09_24_2022_12_19_33.txt, pls

**Comment by xzxADIxzx** [comment]
oh, and what mods do you play with?

**Comment by RandomInsultedCoder** [comment]
ok ill send it rn
[crash-report-09_25_2022_20_02_11.txt](https://github.com/xzxADIxzx/Scheme-Size/files/9646185/crash-report-09_25_2022_20_02_11.txt)
ignore v135.2 and lower version mods

**Comment by xzxADIxzx** [comment]
huh, error due to testing utils mod, the beautiful name of the ui elements in it and my _schizophrenia_...
well, i'll fix it in next update
