### ISSUE TITLE
Wave menu still there

### ISSUE THREAD

**Issue by SparkdotIe** [xzxADIxzx/Scheme-Size#29]
Even with disabling the wave notification, the menu is still there, blocking building where it is. Along with that, the button for more information is still clickable, even when the menu is hidden

https://user-images.githubusercontent.com/26665237/193152174-98ae26e5-30d8-4713-9623-e8ef6c73d865.mp4

**Comment by xzxADIxzx** [comment]
thanks for your report :3
i'll fix it today

**Comment by xzxADIxzx** [comment]
i just fixed it :3
1f71d143b4038a68fef1fe7ac1fceff2213f2787
