### ISSUE TITLE
v2.7.7 crash on PC

### ISSUE THREAD

**Issue by Virus5600** [xzxADIxzx/Scheme-Size#33]
**Description**
I've just updated the mod and I managed to play fine but after reinitializing the game, it started crashing. The logs say it's from the new version of scheme-size mod.

Here's the crash report:
[crash-report-01_02_2023_18_09_31.txt](https://github.com/xzxADIxzx/Scheme-Size/files/10330984/crash-report-01_02_2023_18_09_31.txt)

**Steps to reproduce**
Just load the 2.7.7 mod on Mindustry and it will crash the game.

**Other Information**
Laptop Windows 10
Played and initialized from steam

**Comment by xzxADIxzx** [comment]
Thanks for you report, I'll try to fix it today.
Hm, the problem is in steam version of the game, but I downloaded it from itch.io...

**Comment by xzxADIxzx** [comment]
Yup, i fixed it, just update mod.
