### ISSUE TITLE
2r2t Disabled JSMods

### ISSUE THREAD

**Issue by yoloking1111** [xzxADIxzx/Scheme-Size#34]
Hello, may you please send me the list of commands the mod is using since 2r2t disabled mods? thanks.

**Comment by xzxADIxzx** [comment]
What is 2r2t? Okay...
Admin functions of the mod can be executed in three different ways:
One is for local games, the second one uses the **/js** command, and the third one works with the Darkdustry plugin, which contains a lot of commands.
Which one of these are you looking for?

**Comment by yoloking1111** [comment]
> 

2r2t is a anarchy server, and im looking for the js commands the /js part is using

**Comment by xzxADIxzx** [comment]
See https://github.com/xzxADIxzx/Scheme-Size/blob/main/src/java/scheme/tools/admins/SlashJs.java
