### ISSUE TITLE
UI broke

### ISSUE THREAD

**Issue by AzmeurYahigai** [xzxADIxzx/Scheme-Size#35]
Latest version of Jan 20

**Comment by AzmeurYahigai** [comment]
Latest version of Jan 20

![Screenshot_2023-01-20-10-26-27-11_13f989b68d7412e5a177fb13b36ac66f](https://user-images.githubusercontent.com/65272142/213606215-8d81be1f-142c-4558-99bf-c22ac8ae9dba.jpg)

**Comment by xzxADIxzx** [comment]
How did you even do it?
Do you have any other mods?
Can you reproduce the bug?

**Comment by AzmeurYahigai** [comment]
I use both MinerTools and SchemeSize. Earlier MinerTools notified me an update, so I updated it and updated SchemeSize as well. For now I think it was the new MinerTools who caused the issue. Anyways, can you add a switch in settings to hide that tab instead? Sometimes I accidentally press the node help when trying to press the unbuild button.

**Comment by xzxADIxzx** [comment]
The bug appears every time you enter the game?
Well, I'll try to reproduce and fix it.

**Comment by xzxADIxzx** [comment]
Well, I ran into a little problem: the new version of the mod doesn't want to run with the miner tools at all.
Looks like one of the new features completely broke mod compatibility, so what should I do now? :disappointed:

**Comment by AzmeurYahigai** [comment]
Unfortunately, the owner of MinerTools is Chinese and probably doesn't speak English. Maybe put a customizable x y position for the tool tab.

**Comment by xzxADIxzx** [comment]
Maybe you're right. By the way, why play with two mods at once?
If you use some features from miner tools that are not in scheme size, I can add them. It will be much easier ;-;

**Comment by AzmeurYahigai** [comment]
If it's unavoidable, can you please instead add some features from it? Show boosted areas, select ores to mine with Mono AI, or team and block status tab. The 3rd one is optional XD

**Comment by AzmeurYahigai** [comment]
> Maybe you're right. By the way, why play with two mods at once? If you use some features from miner tools that are not in scheme size, I can add them. It will be much easier ;-;

I was thinking so long, couldn't read this sooner lol

**Comment by xzxADIxzx** [comment]
I think the first and second will be easy to do :D

**Comment by xzxADIxzx** [comment]
I'll start work right now :+1:

**Comment by AzmeurYahigai** [comment]
> 

Cool, thanks

**Comment by xzxADIxzx** [comment]
![image](https://user-images.githubusercontent.com/76255437/213879069-395093f0-e8c7-4a8e-a55a-df9c3844bf4e.png)
![image](https://user-images.githubusercontent.com/76255437/213879091-f5e3bf99-ddf6-4f2d-9c6b-41fa6395b496.png)
One of two features ready.

**Comment by xzxADIxzx** [comment]
![image](https://user-images.githubusercontent.com/76255437/213911944-074b7ce0-8ca8-44cc-b67d-ad409331a104.png)
![image](https://user-images.githubusercontent.com/76255437/213913189-27dada39-37d4-40c1-ab8d-3f6037a28f72.png)
Second features is ready :tada:

**Comment by xzxADIxzx** [comment]
I just have to add a warning about the incompatibility of mods and it will be possible to release the mod update.
Is your issue solved?

**Comment by AzmeurYahigai** [comment]
> I just have to add a warning about the incompatibility of mods and it will be possible to release the mod update. Is your issue solved?

Yep, thank you

**Comment by xzxADIxzx** [comment]
I am glad to help :3
