### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by ColaHz** [xzxADIxzx/Scheme-Size#38]
The region rebuild function does not work correctly if the mod is activated

**Comment by xzxADIxzx** [comment]
What is the region rebuild function?
I have absolutely no idea what you're talking about.

**Comment by xzxADIxzx** [comment]
And btw what is your native language?

**Comment by ColaHz** [comment]
.-. 
settings/controls/general
![image](https://user-images.githubusercontent.com/87813567/213875742-bd5f6fd0-77ff-43e4-8f30-a6a07617c0a8.png)

**Comment by xzxADIxzx** [comment]
Oh my god, such great feature...
Why am I finding out about her only now?

**Comment by xzxADIxzx** [comment]
Well, this function works with the mod, just selection isn't displayed ;-;

**Comment by xzxADIxzx** [comment]
Fixed, see 8f7c89567b2e53b214d67f111b99a6488edd18cd
