### ISSUE TITLE
Scheme Size for IOS

### ISSUE THREAD

**Issue by Chebyrek180808** [xzxADIxzx/Scheme-Size#39]
Мне лень писать на английском, из-за того что я знаю что среди вас есть русские ребята, короче, можете пожалуйста забабахать схем сайз для миндастри на айос?

**Comment by xzxADIxzx** [comment]
Интересно... открыл issue и сам же сразу же закрыл.
Но если отвечать на твой вопрос, то я честно не знаю как это сделать ._.
Т.е. ios не поддерживает моды как таковые в принципе, ибо его версия jre, насколько я знаю, не может импортировать сторонние jar файлы; и из-за этого модификация игры на этой платформе не возможна.
Единственным выходом, вероятно, остаётся пересобрать всю игру и распространять отдельно от оригинала ;-;
