### ISSUE TITLE
Needs update

### ISSUE THREAD

**Issue by XxsuperdeadlysniperxX** [xzxADIxzx/Scheme-Size#41]
Plz update

**Comment by XxsuperdeadlysniperxX** [comment]
Can you see about fixing some random crashing on android?

**Comment by XxsuperdeadlysniperxX** [comment]
Thats one thing

**Comment by XxsuperdeadlysniperxX** [comment]
Not trying to force you or anything i really don't like that

**Comment by xzxADIxzx** [comment]
There are no fixes specifically for android, but if you **really** need it...
