### ISSUE TITLE
mindustry freezing/hanging when using the paint brush

### ISSUE THREAD

**Issue by coder1454** [xzxADIxzx/Scheme-Size#42]
so when trying to paint a large circle mindustry will hang.

**Comment by coder1454** [comment]
oh and maybe add threads too all the other ones that uses for or any thing like it

**Comment by xzxADIxzx** [comment]
How big is the circle? I have never had such problems, maybe because I never really used really big brushes...
Nevermind, I'll add multithreading in a next update if I find performance issues

**Comment by xzxADIxzx** [comment]
Oh, and what is your native language?

**Comment by coder1454** [comment]
my  native language is english
and idk cuase i dont use it i play on a server called 2r2t and lots of the time if there are scheme users on they will build too big of a circle and crash everyone and half the time the server

**Comment by coder1454** [comment]
oh and i use foo so i cant use it even if wanted to lol

**Comment by xzxADIxzx** [comment]
hm, understandable...
I never thought that some psychos would fill so much space, but in any case, I heard you

**Comment by xzxADIxzx** [comment]
I will add multithreading and check that the tile already has been changed

**Comment by coder1454** [comment]
thanks

**Comment by coder1454** [comment]
guess i can close this now
