### ISSUE TITLE
SS block surface tile building if they're revealed in map settings

### ISSUE THREAD

**Issue by rekokoro** [xzxADIxzx/Scheme-Size#47]
If surface blocks and tiles are revealed in map settings, mod prevents to placing them ingame, even if vanilla mindustry players can do it.

**Comment by xzxADIxzx** [comment]
Sorry for taking so long to answer, I'm a little lost in myself ,_,
I will fix this bug tomorrow or after tomorrow :3

**Comment by xzxADIxzx** [comment]
Done ec5ceec
