### ISSUE TITLE
arc.scene.ui.layout.Table cannot be cast to class arc.scene.ui.layout.Stack

### ISSUE THREAD

**Issue by Matias-F123** [xzxADIxzx/Scheme-Size#51]
Hello, i made this (probably) duplicate of #50 to add the logs so u can track the issue :)

[crash-report-05_12_2023_00_26_49.txt](https://github.com/xzxADIxzx/Scheme-Size/files/11458619/crash-report-05_12_2023_00_26_49.txt)

(This happens in 143.1, and 144 seems fine)

**Comment by xzxADIxzx** [comment]
The mod on v144 was throwing an error so I updated it but forgot to change minGameVersion in mod.json.
Therefore, you can still run it on the old version of the game, although you should not.

**Comment by xzxADIxzx** [comment]
Just update the game or download an older version of the mod.
I'm sorry for the inconvenience.

**Comment by Matias-F123** [comment]
That's ok, thank u, ill close the issue then
