### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by Up-an-Down** [xzxADIxzx/Scheme-Size#54]
![image](https://github.com/xzxADIxzx/Scheme-Size/assets/104922829/fc6cd33f-04d1-4ef0-aa85-c21f696f7a41)

[crash-report-05_18_2023_22_04_20.txt](https://github.com/xzxADIxzx/Scheme-Size/files/11510865/crash-report-05_18_2023_22_04_20.txt)
Windows 10, Game ver: 144.1, Mod ver: latest

**Comment by xzxADIxzx** [comment]
Looks like the mod is searching for non-existent file

**Comment by Up-an-Down** [comment]
But how to fix it?

**Comment by Up-an-Down** [comment]
Something happened (maybe mindustry/mod update?) and this was fixed!

**Comment by xzxADIxzx** [comment]
Ahaha
