### ISSUE TITLE
Where?

### ISSUE THREAD

**Issue by 1stvaliduser** [xzxADIxzx/Scheme-Size#7]
Where is "Secret Settings"?

**Comment by xzxADIxzx** [comment]
default key is F12, see in control settings

**Comment by 1stvaliduser** [comment]
> default key is F12, see in control settings

I'm using my phone.

**Comment by xzxADIxzx** [comment]
![image](https://user-images.githubusercontent.com/76255437/155204142-30372ded-3b5c-44ac-a3e2-996f97e27c47.png)
