### ISSUE TITLE
Not work with mods.

### ISSUE THREAD

**Issue by Creater3d** [xzxADIxzx/Scheme-Size#8]
Need fix.

**Comment by xzxADIxzx** [comment]
1. What mods are you talking about? It doesn't work with whole range
2. I plan to rewrite the entire code. _some day_
3. I'm too lazy, sorry...

**Comment by Creater3d** [comment]
> 1. What mods are you talking about? It doesn't work with whole range
> 2. I plan to rewrite the entire code. _some day_
> 3. I'm too lazy, sorry...

I mean it is just with vanila, with mods i not can see items in work blocks.

**Comment by xzxADIxzx** [comment]
> not can

Is your native language Russian?

**Comment by xzxADIxzx** [comment]
> https://github.com/MEEPofFaith/prog-mats-java/issues/15

Yes, it is...

**Comment by xzxADIxzx** [comment]
> I mean it is just with vanila, with mods i not can see items in work blocks.

What is _work blocks_?!
